# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking.
  config.vm.box_check_update = false
  
  # Access
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  # Create a forwarded port mapping which allows access to a specific port
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 1
  end
  
  # Enable provisioning with a shell script
  
  # Enable provisioning with docker
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/downloads/ckan/contrib/docker/docker-compose.yml", run: "always"

end
