# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking.
  # config.vm.box_check_update = false
  
  # Access
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  # Create a forwarded port mapping which allows access to a specific port
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    #vb.memory = "2048"
	vb.memory = "4096"
    vb.cpus = 2
  end
  
  #
  # Enable provisioning with a shell script
  #
  config.vm.provision "shell", path: "provision/setup-general.sh"
  config.vm.provision "shell", path: "provision/setup-java.sh"
  config.vm.provision "shell", path: "provision/setup-postgresql.sh"
  #config.vm.provision "shell", path: "provision/setup-postgresql-extra-configs.sh" # optional
  config.vm.provision "shell", path: "provision/setup-pentaho-ce.sh"
  config.vm.provision "shell", path: "provision/setup-pentaho-data-integration.sh"
  #config.vm.provision "shell", path: "provision/setup-pentaho-report-designer.sh" # optional
  
  # uncomment the following line if you need to have a Ubuntu with running desktop GUI
  #config.vm.provision "shell", path: "provision/setup-ubuntu-desktop.sh"
  
  # another option to Install packaged to display / GUI
  #config.vm.provision "shell", path: "provision/setup-tiny-desktop.sh"
  
end
