# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #	hack to work with older vagrant (without powershell 3.0)
  config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/bionic64"
  
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
  
  # Access
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  # Create a forwarded port mapping which allows access to a specific port
  #config.vm.network "forwarded_port", guest: 5432, host: 5432
  #config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Enable provisioning with a shell script
  config.vm.provision "shell", path: "provision/setup-general.sh"
  config.vm.provision "shell", path: "provision/setup-java.sh"
  config.vm.provision "shell", path: "provision/setup-apama-ce.sh"
end
