# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "bento/ubuntu-18.04"
  

  # Disable automatic box update checking.
  config.vm.box_check_update = false
  
  # Access
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  # Create a forwarded port mapping which allows access to a specific port
  config.vm.network "forwarded_port", guest: 8787, host: 8787

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 1
  end

  # Enable provisioning with a shell script
  config.vm.provision "shell", path: "provision/setup-general.sh"
  config.vm.provision "shell", path: "provision/setup-java.sh"
  config.vm.provision "shell", path: "provision/setup-dev-env.sh"
  config.vm.provision "shell", path: "provision/setup-modeldb.sh"
end
