# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #	hack to work with older vagrant (without powershell 3.0)
  config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/bionic64"
  
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"

  # Disable automatic box update checking.
  config.vm.box_check_update = false
  
  # Access
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  # Create a forwarded port mapping which allows access to a specific port
  config.vm.network "forwarded_port", guest: 8088 , host: 8088

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 1
  end
  
  # Enable provisioning with a shell script
  config.vm.provision "shell", path: "provision/setup-general.sh"
  config.vm.provision "shell", path: "provision/setup-dev-env.sh"
  config.vm.provision "shell", path: "provision/setup-docker.sh"
  config.vm.provision "shell", path: "provision/setup-superset-git-once.sh" # requires manual interaction, because of the fabmanager
  
  
  # Enable provisioning with docker
  # config.vm.provision :docker
  # config.vm.provision :docker_compose, yml: "/vagrant/downloads/incubator-superset/contrib/docker/docker-compose.yml", run: "always"
  
  # On boot
  # config.vm.provision "shell", path: "provision/run-docker-superset.sh", run: "always"

end
