Vagrant.configure(2) do |config|

	config.vm.box = "hashicorp/precise64"
	# port for Jupyter Notebook
	config.vm.network "forwarded_port", guest: 8888, host: 8888
	# port for WinSCP or Putty
	config.vm.network "forwarded_port", guest: 22, host: 2294
	
	# Shell provisioning
    config.vm.provision "shell" do |s|
    	s.path = "provision/setup.sh"
    end
	
	config.vm.synced_folder "shared/", "/home/vagrant/shared/"
	
end