# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	#hack to work with older vagrant (without powershell 3.0)
	config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/bionic64"
	
	#config.vm.box = "ubuntu/xenial64"	
	#config.vm.box = "hashicorp/precise64"
	config.vm.box = "ubuntu/bionic64"
	
	#port for Jupyter Notebook
	config.vm.network "forwarded_port", guest: 8888, host: 8888
	
	# port for WinSCP or Putty
	config.vm.network "forwarded_port", guest: 22, host: 2294
	
	# Enable provisioning with a shell script
	config.vm.provision "shell", path: "provision/setup-general.sh"
	config.vm.provision "shell", path: "provision/setup-dev-env.sh"
	config.vm.provision "shell", path: "provision/setup-anaconda.sh"
	
	# config.vm.synced_folder "shared/", "/home/vagrant/shared/"
	
	# On boot
	config.vm.provision "shell", path: "provision/run-jupyter-notebook.sh", run: "always"
	
end

